// MetenTVProtect.idl : MetenTVProtect 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(MetenTVProtect.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(6DE76F8E-E6FE-4F5F-9338-455DB1BE8C10),
	version(1.0),
]
library MetenTVProtectLib
{
	importlib("stdole2.tlb");
};

